spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ExamChrono
    username: loubna
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: loubnarachid1717gmail.com
    password: pxmq eeok szdj tyoe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true